
logging:
  level:
    root: info
spring:
  messages:
    basename: errors
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/study_group
    username: root
    password: k1651227
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        show_sql: true
        format_sql: true

  mail:
    smtp:
      auth: update
      ssl: true
      starttls:
        enable: true
    host: 'smtp.gmail.com'
    port: 587
    username: 'rnwldnd7248@gmail.com'
    password: 'exoyjqfefwlutwmy'
  devtools:
    restart:
      enabled: false

  rabbitmq:
    password: guest
    port: '5672'
    host: localhost
    username: guest

server:
  port : 8082
  servlet:
    session:
      tracking-modes: cookie
    timeout: 60
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-binding-errors: always
    include-message: always






